In [121]:
import numpy as np

In [122]:
y = np.array([-41.7, 205.7, -122.6, -20.7, 178.2, 204.4, -2.3, 49.1, -151.7, -74.])
y_mean = y.mean()
SST = np.sum((y- y_mean)**2)
SST


np.float64(158914.684)

In [123]:
X = np.array([[5.04, 4.7, 5.95, 3.82],
              [6.13, 5.89, 4.16, 7.3],
              [3.04, 5.13, 6.34, 3.72],
              [6.0, 4.48, 3.24, 5.19],
              [4.54, 7.1, 4.71, 6.33],
              [5.79, 6.02, 5.91, 6.33],
              [5.26, 5.3, 5.49, 3.65],
              [6.93, 3.6, 4.32, 6.46],
              [4.63, 3.44, 3.77, 5.59],
              [3.09, 5.62, 4.39, 5.27]])

In [124]:
x1 = X[:,1]
x1


array([4.7 , 5.89, 5.13, 4.48, 7.1 , 6.02, 5.3 , 3.6 , 3.44, 5.62])

In [125]:
print(y[x1<=4.9])

[ -41.7  -20.7   49.1 -151.7]


In [126]:
group1_tree1 = y[x1<=4.9]
group2_tree1 = y[x1>4.9]
mean_group1_tree1 = np.mean(group1_tree1)
mean_group2_tree1 = np.mean(group2_tree1)
Tree_One_SSE = np.sum((group1_tree1 - mean_group1_tree1)**2)+np.sum((group2_tree1 - mean_group2_tree1)**2)
Tree_One_SSE 


np.float64(131871.90999999997)

In [127]:
import numpy as np

# Data from the table
X = np.array([[5.04, 4.7, 5.95, 3.82],
              [6.13, 5.89, 4.16, 7.3],
              [3.04, 5.13, 6.34, 3.72],
              [6.0, 4.48, 3.24, 5.19],
              [4.54, 7.1, 4.71, 6.33],
              [5.79, 6.02, 5.91, 6.33],
              [5.26, 5.3, 5.49, 3.65],
              [6.93, 3.6, 4.32, 6.46],
              [4.63, 3.44, 3.77, 5.59],
              [3.09, 5.62, 4.39, 5.27]])

y = np.array([-41.7, 205.7, -122.6, -20.7, 178.2, 204.4, -2.3, 49.1, -151.7, -74])

# Calculate SST
y_mean = np.mean(y)
SST = np.sum((y - y_mean) ** 2)

# Tree One: split on x1 <= 4.9
x1 = X[:, 0]
group1_tree1 = y[x1 <= 4.9]
group2_tree1 = y[x1 > 4.9]
mean_group1_tree1 = np.mean(group1_tree1)
mean_group2_tree1 = np.mean(group2_tree1)
SSE_tree1 = np.sum((group1_tree1 - mean_group1_tree1) ** 2) + np.sum((group2_tree1 - mean_group2_tree1) ** 2)
SSE_tree1

group1_tree1

array([-122.6,  178.2, -151.7,  -74. ])

In [128]:
#Tree Two: split on x2 <= 5.3

x2 = X[:, 1]
group1_tree2 = y[x2 <=5.3]
group2_tree2 = y[x2 >5.3]
mean_group1_tree2 = y[x2<=5.3].mean()
mean_group2_tree2 = y[x2>5.3].mean()
SSE_tree2_group1 = np.sum((group1_tree2 - mean_group1_tree2 )**2)
SSE_tree2_group2 = np.sum((group2_tree2 - mean_group2_tree2 )**2)
SSE_tree2_group1 + SSE_tree2_group2



np.float64(83817.09583333333)

In [129]:
import numpy as np
x = np.array([0.5, 1.3, 1.5, 2.7, 3.1, 3.3, 3.9, 6., 6.8, 7.3, 7.4, 9.9])
y = np.array([2, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0])
def get_proportions(y):
    counts = np.array([np.sum(y == i) for i in np.unique(y)])
    return counts / len(y)
array_gini = get_proportions(y)
print(array_gini)

[0.66666667 0.08333333 0.25      ]


In [130]:
logs = np.log2(array_gini)

entropy = - np.sum(array_gini * logs)
entropy


np.float64(1.188721875540867)

In [131]:
condition = x <= 6.4

x_left = x[condition]
y_left = y[condition]
y_left


array([2, 1, 0, 2, 2, 0, 0, 0])

In [132]:
def get_proportions(y_left):
    counts = np.array([np.sum(y_left == i) for i in np.unique(y)])
    return counts / len(y_left)
array_gini_left = get_proportions(y_left)
print(array_gini_left)

logs_left = np.log2(array_gini_left)

entropy_left = - np.sum(array_gini_left * logs_left)
entropy_left


[0.5   0.125 0.375]


np.float64(1.4056390622295665)

In [133]:
x_right = x[~condition]
y_right = y[~condition]
y_right


array([0, 0, 0, 0])

In [134]:
def get_proportions(y_right):
    counts = np.array([np.sum(y_right == i) for i in np.unique(y)])
    return counts / len(y_right)
array_gini_right = get_proportions(y_right)
print(array_gini_right)

logs_right = np.log2(array_gini_right)

entropy_right = - np.sum(array_gini_right * logs_right)
entropy_right


[1. 0. 0.]


/var/folders/x_/71wrj7jx5474n6st5fwkvj7r0000gn/T/ipykernel_37458/252855636.py:7: RuntimeWarning: divide by zero encountered in log2
  logs_right = np.log2(array_gini_right)
/var/folders/x_/71wrj7jx5474n6st5fwkvj7r0000gn/T/ipykernel_37458/252855636.py:9: RuntimeWarning: invalid value encountered in multiply
  entropy_right = - np.sum(array_gini_right * logs_right)


np.float64(nan)

In [136]:
tree_entropy = entropy_left * len(y_left)/len(y)

tree_entropy

np.float64(0.9370927081530444)